# sudo docker compose -f docker-compose.video-streaming.yml up -d

name: "video-streaming"
services:

  rtsp-to-hls-converter:
    environment:
      - HOSTNAME=$(hostname)  # Значение подставится ТОЛЬКО при сборке
    build:
      context: VideoStreaming/Zs.RtspToHlsConverter
    restart: always
    volumes:
      - "/opt/videos:/opt/videos/"

  web-api:
    environment:
      - HOSTNAME=$(hostname)  # Значение подставится ТОЛЬКО при сборке
    build:
      context: VideoStreaming/Zs.VideoPlayer.WebApi
    ports:
      - "6001:80"
    depends_on:
      - rtsp-to-hls-converter
    restart: always
    volumes:
      - "/opt/videos:/opt/videos/"

  client-app:
    environment:
      - HOSTNAME=$(hostname)  # Значение подставится ТОЛЬКО при сборке
    build:
      context: VideoStreaming/Zs.VideoPlayer.ClientApp
    ports:
      - "6002:80"
    depends_on:
      - web-api
    restart: always
