# sudo docker compose -f docker-compose.home.yml up -d

name: "home"
services:

  web-api:
    image: home.web-api
    container_name: home-web-api
    environment:
      - HOSTNAME=${HOSTNAME}  # Предварительно выполнить на хосте: echo "HOSTNAME=$(hostname)" > .env
    build:
      context: .
      dockerfile: Home/Zs.Home.WebApi/Dockerfile
      platforms:
        - linux/arm64
    ports:
      - "6024:80"
    restart: unless-stopped
    volumes:
      - /opt/configs:/opt/configs:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /dev:/host/dev:ro
      - /run:/host/run:ro
      - /usr/sbin/smartctl:/usr/sbin/smartctl:ro
    pid: host
    privileged: true
    user: "0:0"

  bot:
    image: home.bot
    container_name: home-bot
    environment:
      - HOSTNAME=${HOSTNAME}  # Предварительно выполнить на хосте: echo "HOSTNAME=$(hostname)" > .env
    build:
      context: .
      dockerfile: Home/Zs.Home.Bot/Dockerfile
      platforms:
        - linux/arm64
    ports:
      - "6022:80"
    depends_on:
      - web-api
    restart: unless-stopped
    volumes:
      - "/opt/configs:/opt/configs/:ro"

  jobs:
    image: home.jobs-hangfire
    container_name: home-jobs
    environment:
      - HOSTNAME=${HOSTNAME}  # Предварительно выполнить на хосте: echo "HOSTNAME=$(hostname)" > .env
    build:
      context: .
      dockerfile: Home/Zs.Home.Jobs.Hangfire/Dockerfile
      platforms:
        - linux/arm64
    ports:
      - "6023:80"
    depends_on:
      - web-api
    restart: unless-stopped
    volumes:
      - "/opt/configs:/opt/configs/:ro"

  client-app:
    image: home.client-app
    container_name: home-client-app
    environment:
      - HOSTNAME=${HOSTNAME}  # Предварительно выполнить на хосте: echo "HOSTNAME=$(hostname)" > .env
    build:
      context: .
      dockerfile: Home/Zs.Home.ClientApp/Dockerfile
      platforms:
        - linux/arm64
    ports:
      - "6021:80"
    restart: unless-stopped
    volumes:
      - "/opt/configs:/opt/configs/:ro"
