# sudo docker compose -f docker-compose.infrastructure.yml up -d

# 1. Эти каталоги будут созданы автоматически, но надо раздать права:
# sudo mkdir -p /opt/infrastructure/{portainer,postgresql,kafka,rabbitmq,prometheus,grafana}/{data,configs}
# sudo chmod -R 777 /opt/infrastructure/

# 2. prometheus.yml из Solution Items разместить в /opt/infrastructure/prometheus/configs/prometheus.yml

# 3. grafana.ini из Solution Items разместить в /opt/infrastructure/grafana/configs/
#sudo chown 472:472 /opt/infrastructure/grafana/configs/grafana.ini
#sudo chmod 644 /opt/infrastructure/grafana/configs/grafana.ini


name: "infrastructure"

networks:
  infra-network:
    driver: bridge

services:
  # TODO: ELK Stack

  # -----------------------------------------
  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION:-latest}
    container_name: portainer
    restart: unless-stopped
    ports:
      - "8000:8000" # Порт для туннелей
      - "${PORTAINER_PORT_HTTP:-9000}:9000" # HTTP UI
      # - "${PORTAINER_PORT_HTTPS:-9443}:9443" # HTTPS UI
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Доступ к Docker API для управления
      - /opt/infrastructure/portainer/data:/data # Данные Portainer
    networks:
      - infra-network

  # ----------------------------------------- Если Portainer есть на другой машине
  portainer-agent:
    image: portainer/agent:latest
    container_name: portainer_agent
    restart: unless-stopped
    ports:
      - "${PORTAINER_AGENT_HTTP:-9001}:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - infra-network

  # -----------------------------------------
  postgresql:
    image: postgres:${POSTGRES_VERSION:-latest}
    container_name: postgresql
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - /opt/infrastructure/postgresql/data:/var/lib/postgresql/data
      - /opt/infrastructure/postgresql/configs:/etc/postgresql
    networks:
      - infra-network

  # -----------------------------------------
  kafka:
    image: confluentinc/cp-kafka:${KAFKA_VERSION:-latest}
    container_name: kafka
    restart: unless-stopped
    ports:
      - "${KAFKA_PORT:-9092}:9092" # Для доступа извне
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:${KAFKA_PORT:-9092},CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${HOST_IP:-localhost}:${KAFKA_PORT:-9092}
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: ${KAFKA_REPLICATION_FACTOR:-1}
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: ${KAFKA_MIN_ISR:-1}
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - /opt/infrastructure/kafka/data:/var/lib/kafka/data
      - /opt/infrastructure/kafka/configs:/etc/kafka
    networks:
      - infra-network

  # -----------------------------------------
  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: kafka-exporter
    restart: unless-stopped
    ports:
      - "${KAFKA_EXPORTER_PORT:-9308}:9308"
    command:
      - --kafka.server=kafka:${KAFKA_PORT:-9092}
    depends_on:
      - kafka
    networks:
      - infra-network

  # -----------------------------------------
  kafka-ui:
    image: provectuslabs/kafka-ui:${KAFKA_UI_VERSION:-latest}
    container_name: kafka-ui
    restart: unless-stopped
    ports:
      - "${KAFKA_UI_PORT:-8080}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: ${KAFKA_CLUSTER_NAME:-local}
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:${KAFKA_PORT:-9092}
      #KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:${ZOOKEEPER_CLIENT_PORT:-2181} # Адрес Zookeeper для UI (опционально)
      DYNAMIC_CONFIG_ENABLED: "true"
    depends_on:
      - kafka
    networks:
      - infra-network

  # -----------------------------------------
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION:-4-management-alpine}
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "${RABBITMQ_AMQP_PORT:-5672}:5672"
      - "${RABBITMQ_UI_PORT:-15672}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-admin}
    volumes:
      - /opt/infrastructure/rabbitmq/data:/var/lib/rabbitmq
    networks:
      - infra-network

  # -----------------------------------------
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "${NODE_EXPORTER_PORT:-9100}:9100"
    networks:
      - infra-network

  # -----------------------------------------
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    ports:
      - "${CADVISOR_PORT:-8080}:8080"
    networks:
      - infra-network

  # -----------------------------------------
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-latest}
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090" # UI
    volumes:
      - /opt/infrastructure/prometheus/configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - /opt/infrastructure/prometheus/data:/prometheus
    env_file:
      - .env
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    depends_on:
      - node-exporter
      - cadvisor
    networks:
      - infra-network

  # -----------------------------------------
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION:-latest}
    container_name: grafana
    restart: unless-stopped
    ports:
      - "${GRAFANA_PORT:-3000}:3000" # UI
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
      GF_INSTALL_PLUGINS: ${GRAFANA_PLUGINS:-}
    volumes:
      - /opt/infrastructure/grafana/data:/var/lib/grafana
      - /opt/infrastructure/grafana/configs:/etc/grafana
    networks:
      - infra-network
