services:

  rtsp-to-hls-converter:
    environment:
      - HOSTNAME=$(hostname)  # Значение подставится ТОЛЬКО при сборке
    build:
      context: ./Zs.RtspToHlsConverter
    restart: always
    volumes:
      - "/var/lib/videos:/var/lib/videos"

  web-api:
    environment:
      - HOSTNAME=$(hostname)  # Значение подставится ТОЛЬКО при сборке
    build:
      context: ./Zs.VideoPlayer.WebApi
    ports:
      - "6001:80"
    depends_on:
      - rtsp-to-hls-converter
    restart: always
    volumes:
      - "/var/lib/videos:/var/lib/videos"

  client-app:
    environment:
      - HOSTNAME=${HOSTNAME}  # Предварительно выполнить на хосте: echo "HOSTNAME=$(hostname)" > .env
    build:
      context: ./Zs.VideoPlayer.ClientApp
    ports:
      - "6002:80"
    depends_on:
      - web-api
    restart: always
