[server]
root_url = %(protocol)s://%(domain)s:%(http_port)s/

[database]
; Чистая установка создаст SQLite базу в /var/lib/grafana/grafana.db

[security]
admin_user = ${GF_SECURITY_ADMIN_USER}
admin_password = ${GF_SECURITY_ADMIN_PASSWORD}

[paths]
data = /var/lib/grafana
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning
