version: '3'
services:

  rtsp-to-hls-converter:
    build:
      context: ./Zs.RtspToHlsConverter
    restart: always
    volumes:
      - "/var/lib/videos:/var/lib/videos"

  web-api:
    build:
      context: ./Zs.VideoPlayer.WebApi
    ports:
      - "6001:80"
    depends_on:
      - rtsp-to-hls-converter
    restart: always
    volumes:
      - "/var/lib/videos:/var/lib/videos"

  client-app:
    build:
      context: ./Zs.VideoPlayer.ClientApp
    ports:
      - "6002:80"
    depends_on:
      - video-player-api
    restart: always
