services:

  bot:
    build:
      context: ./Zs.Home.Bot
    restart: always

  client-app:
    build:
      context: ./Zs.Home.ClientApp
    ports:
      - "6021:80"
    restart: always
    volumes:
      - "/opt/configs:/opt/configs/:ro" # for external configurations
